name: Slack Event Trigger Test

on:
  repository_dispatch:
    types:
      - event-trigger

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: "C03LF4N5WES"
  CLIENT-PAYLOAD: ${{ github.event.client_payload }}

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Dump event
        run: echo CLIENT-PAYLOAD
  send-notification:
    name: "Send Slack Notification"
    runs-on: ubuntu-latest
    steps:
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@46098c76608e7ab2e5c784a0e93fd44065b20ab3
        with:
            status: "Hello" # ${{ job.status }} # or a string such as `in-process`
            channel: SLACK_CHANNEL
            message: "#Triggered\n\nCLIENT-PAYLOAD"
        if: always()  # <<<< ALWAYS RUN THIS STEP EVEN IF PREVIOUS STEPS FAILED
