name: Slack Slash Test - Configuration Check

on:
  repository_dispatch:
    types:
      - configuration-check

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  CLIENT-PAYLOAD: ${{ github.event.client_payload }}
  SLACK_CHANNEL: "C03LF4N5WES"

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo Hello
  send-notification:
    name: "Send Slack Notification"
    runs-on: ubuntu-latest
    steps:
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@46098c76608e7ab2e5c784a0e93fd44065b20ab3
        with:
            status: "Hello" # ${{ job.status }} # or a string such as `in-process`
            channel: SLACK_CHANNEL
            message: "${{ env.CLIENT-PAYLOAD }}"
        if: always()  # <<<< ALWAYS RUN THIS STEP EVEN IF PREVIOUS STEPS FAILED
